In [2]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
pd.set_option('display.max_columns', None)

data = pd.read_excel('nba_player_data.xlsx')

In [3]:
data.sample(10)

,Year,Season_type,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
5963,2020-21,Regular%20Season,1630166,272,Deni Avdija,1610612764,WAS,54,1257,130,312,0.417,53,168,0.315,29,45,0.644,22,240,262,63,32,15,33,140,342,483,1.91,0.97
5214,2019-20,Regular%20Season,1628960,269,Grayson Allen,1610612763,MEM,38,718,117,251,0.466,57,141,0.404,39,45,0.867,8,77,85,52,10,2,33,53,330,306,1.58,0.30
4592,2018-19,Regular%20Season,1629004,389,Svi Mykhailiuk,1610612765,DET,42,440,46,140,0.329,29,89,0.326,12,20,0.600,9,27,36,37,14,1,21,25,133,98,1.76,0.67
4136,2017-18,Playoffs,203526,142,Raul Neto,1610612762,UTA,8,72,7,23,0.304,2,7,0.286,5,5,1.000,2,8,10,10,2,0,4,7,21,23,2.50,0.50
1454,2014-15,Regular%20Season,101114,93,Deron Williams,1610612751,BKN,68,2114,298,771,0.387,87,237,0.367,201,241,0.834,29,208,237,448,64,17,154,157,884,983,2.91,0.42
1097,2013-14,Regular%20Season,203508,421,Sergey Karasev,1610612739,CLE,22,156,12,35,0.343,4,19,0.211,9,10,0.900,0,16,16,6,3,1,11,22,37,28,0.55,0.27
371,2012-13,Regular%20Season,201944,371,Terrence Williams,1610612738,BOS,24,318,48,97,0.495,5,15,0.333,9,21,0.429,4,40,44,38,11,2,22,13,110,122,1.73,0.50
4608,2018-19,Regular%20Season,1627816,405,Alex Poythress,1610612737,ATL,21,305,40,81,0.494,9,23,0.391,18,29,0.621,29,47,76,17,4,10,13,47,107,149,1.31,0.31
2160,2015-16,Regular%20Season,1626144,99,Emmanuel Mudiay,1610612743,DEN,68,2068,329,905,0.364,74,232,0.319,140,209,0.670,32,200,232,372,65,35,217,141,872,714,1.71,0.30
4553,2018-19,Regular%20Season,201967,350,Dante Cunningham,1610612759,SAS,64,928,75,158,0.475,30,65,0.462,14,18,0.778,48,140,188,50,27,13,22,71,194,363,2.27,1.23

In [4]:
data.shape

(7293, 30)

In [5]:
data.isna().sum()

Year           0
Season_type    0
PLAYER_ID      0
RANK           0
PLAYER         0
TEAM_ID        0
TEAM           0
GP             0
MIN            0
FGM            0
FGA            0
FG_PCT         0
FG3M           0
FG3A           0
FG3_PCT        0
FTM            0
FTA            0
FT_PCT         0
OREB           0
DREB           0
REB            0
AST            0
STL            0
BLK            0
TOV            0
PF             0
PTS            0
EFF            0
AST_TOV        0
STL_TOV        0
dtype: int64

In [10]:
## Data cleaning & analysis prep

data.drop(columns=['RANK','EFF'], inplace=True)

In [11]:
data['season_start_year'] = data['Year'].str[:4].astype(int)

In [9]:
data.TEAM.nunique()

31

In [13]:
data['TEAM'].replace(to_replace=['NOP','NOH'], value= 'NO', inplace=True)

In [14]:
data['Season_type'].replace('Regular%20Season', 'RS', inplace=True)

In [16]:
data[data['Season_type'] == 'RS']

,Year,Season_type,PLAYER_ID,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,AST_TOV,STL_TOV,season_start_year
0,2012-13,RS,201142,Kevin Durant,1610612760,OKC,81,3119,731,1433,0.510,139,334,0.416,679,750,0.905,46,594,640,374,116,105,280,143,2280,1.34,0.41,2012
1,2012-13,RS,977,Kobe Bryant,1610612747,LAL,78,3013,738,1595,0.463,132,407,0.324,525,626,0.839,66,367,433,469,106,25,287,173,2133,1.63,0.37,2012
2,2012-13,RS,2544,LeBron James,1610612748,MIA,76,2877,765,1354,0.565,103,254,0.406,403,535,0.753,97,513,610,551,129,67,226,110,2036,2.44,0.57,2012
3,2012-13,RS,201935,James Harden,1610612745,HOU,78,2985,585,1337,0.438,179,486,0.368,674,792,0.851,62,317,379,455,142,38,295,178,2023,1.54,0.48,2012
4,2012-13,RS,2546,Carmelo Anthony,1610612752,NYK,67,2482,669,1489,0.449,157,414,0.379,425,512,0.830,134,326,460,171,52,32,175,205,1920,0.98,0.30,2012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7071,2021-22,RS,1630207,Nate Hinton,1610612754,IND,2,2,0,1,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,1,0,0,0.00,0.00,2021
7072,2021-22,RS,1626155,Sam Dekker,1610612761,TOR,1,1,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0.00,0.00,2021
7073,2021-22,RS,1629309,Trayvon Palmer,1610612765,DET,1,17,0,1,0.000,0,0,0.000,0,0,0.000,0,2,2,0,0,0,1,2,0,0.00,0.00,2021
7074,2021-22,RS,1629788,Tyler Hall,1610612752,NYK,1,2,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0.00,0.00,2021
7075,2021-22,RS,1629597,Zylan Cheatham,1610612762,UTA,1,5,0,3,0.000,0,2,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0.00,0.00,2021

In [17]:
rs_df = data[data['Season_type'] == 'RS']
playoffs_df = data[data['Season_type'] == 'RS']

In [18]:
data.columns

Index(['Year', 'Season_type', 'PLAYER_ID', 'PLAYER', 'TEAM_ID', 'TEAM', 'GP',
       'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA',
       'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF',
       'PTS', 'AST_TOV', 'STL_TOV', 'season_start_year'],
      dtype='object')

In [19]:
total_cols = ['MIN', 'FGM', 'FGA', 'FG3M', 'FG3A', 'FTM', 'FTA',
             'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF',
               'PTS']

In [ ]:
## Which player stats are corelated with each other?

In [ ]:
data.corr()